name: Publish Tile

permissions:
  id-token: write # Required for OIDC token
  contents: read # Required to checkout the repository

on:
  push:
    branches:
      - main # Trigger on push / merge to main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tile:
          - skills/documentation
          - skills/fastify
          - skills/init
          - skills/linting-neostandard-eslint9
          - skills/node
          - skills/nodejs-core
          - skills/oauth
          - skills/octocat
          - skills/skill-optimizer
          - skills/snipgrapher
          - skills/typescript-magician
    steps:
      - uses: actions/checkout@v4
      - uses: tesslio/publish@main
        with:
          token: ${{ secrets.TESSL_API_TOKEN }}
          path: ${{ matrix.tile }}
